name: Update PR Spreadsheet

on:
  pull_request:
    types: [opened, reopened, edited, closed, synchronize]

jobs:
  update-spreadsheet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run script
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        PR_DATA=$(echo '{
          "merged_at": "${{ github.event.pull_request.merged_at }}",
          "html_url": "${{ github.event.pull_request.html_url }}",
          "user_login": "${{ github.event.pull_request.user.login }}",
          "title": "${{ github.event.pull_request.title }}",
          "repo_name": "${{ github.event.pull_request.base.repo.name }}",
          "updated_at": "${{ github.event.pull_request.updated_at }}",
          "requested_reviewers": "${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}",
          "assignees": "${{ join(github.event.pull_request.assignees.*.login, ',') }}",
          "user_site_admin": ${{ github.event.pull_request.user.site_admin }},
          "user_type": "${{ github.event.pull_request.user.type }}",
          "author_association": "${{ github.event.pull_request.author_association }}"
        }' | jq -c .)
        node script.js "$PR_DATA"
